#!/bin/bash
##
# chkconfig: 2345 75 25
# description: havege entropy daemon
#
# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="haveged"

case "$1" in
start)
  echo -n $"Starting $prog: "
  /usr/local/sbin/$prog -w 1024 -v 1 && success || failure
  RETVAL=$?
  [ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
  echo
  ;;

stop)
  echo -n $"Stopping $prog: "
  if [ -e /var/run/$prog.pid ]; then
    kill `cat /var/run/$prog.pid` && success || failure
  else
    failure
  fi
  RETVAL=$?
  [ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
  echo
  ;;

restart)
  $0 stop
  $0 start
  ;;

*)
  echo "usage: $prog [start|stop|restart]"
esac
exit $RETVAL
